packages:
  - antd-dual-theme-manager
  - playground

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild

catalog:
  '@types/node': ^24.0.13
  '@types/react': ^18.3.7
  '@types/react-dom': ^18.3.1
  '@types/lodash-es': ^4.17.12
  typescript: ~5.8.3
  unbuild: ^3.5.0
  vite: ^7.0.0
  '@vitejs/plugin-react': ^4.4.1
  '@vitejs/plugin-react-swc': ^3.8.0
  globals: ^16.0.0
  react: ^18.3.1
  react-dom: ^18.3.1
  eslint: ^9.29.0
  '@eslint/js': ^9.29.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.20
  typescript-eslint: ^8.34.1
